/**
 * P1 scaffold: the "hello dashboard" of spec 00 A1 — it proves the SPA -> FastAPI wiring
 * is live and shows the trust settings the agent will be held to.
 * Replaced by the five screens of spec 11 section 9 in P7.
 */
import { useQuery } from "@tanstack/react-query";

type Health = {
  status: string;
  version: string;
  auto_threshold: number;
  cost_cap_usd_per_run: number;
  model: string;
  llm_mode: "mock" | "live";
  synthetic_data: boolean;
};

export default function App() {
  const { data, isLoading, isError } = useQuery<Health>({
    queryKey: ["health"],
    queryFn: async () => {
      const r = await fetch("/api/health");
      if (!r.ok) throw new Error(`health ${r.status}`);
      return r.json();
    },
  });

  return (
    <div className="mx-auto max-w-3xl px-6 py-14">
      <div className="mb-8 rounded-lg border border-amber-400/30 bg-amber-400/10 px-4 py-2.5 text-sm text-amber-200">
        ⚠️ All data synthetic — generated by ledgerfab. No real financial records.
      </div>

      <h1 className="text-4xl font-semibold text-ink">SpendSort</h1>
      <p className="mt-3 max-w-xl text-ink-muted">
        Expense categorization with confidence gates and a learning vendor memory. Only confident
        decisions auto-apply; the rest go to a review queue.
      </p>

      <div
        className="mt-10 rounded-card border border-hairline bg-glass p-6 backdrop-blur-md"
        style={{ boxShadow: "var(--shadow-glass)" }}
      >
        <h2 className="mb-4 text-sm font-semibold uppercase tracking-wider text-ink-faint">
          Backend
        </h2>

        {isLoading && <p className="text-ink-muted">Checking…</p>}
        {isError && (
          <p className="text-conf-low">
            API unreachable. Start it with <code className="font-mono">make dev</code> (or{" "}
            <code className="font-mono">./make.ps1 dev</code>).
          </p>
        )}

        {data && (
          <dl className="grid grid-cols-2 gap-x-8 gap-y-3 text-sm">
            <Row label="Status" value={data.status} />
            <Row label="Version" value={data.version} />
            <Row label="Auto-apply threshold" value={data.auto_threshold.toFixed(2)} />
            <Row label="Cost cap / run" value={`$${data.cost_cap_usd_per_run.toFixed(2)}`} />
            <Row label="Model" value={data.model} />
            <Row label="LLM mode" value={data.llm_mode} />
          </dl>
        )}
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex items-baseline justify-between gap-4 border-b border-hairline/50 pb-2">
      <dt className="text-ink-faint">{label}</dt>
      <dd className="tabular font-medium text-emerald">{value}</dd>
    </div>
  );
}
