/**
 * aurora `SyntheticDataBanner` — spec 00 A2, and mandatory on every screenshot
 * (spec 00 A1 README order, spec 00 E definition of done, spec 11 section 11).
 *
 * It stays visible rather than being dismissible. A finance demo that could be mistaken for
 * real books is a liability, and the disclaimer is worth more on the screenshot than the
 * pixels it costs.
 *
 * Amber-800 on an amber wash rather than the dark theme's pale amber: 6.6:1 on paper, so the
 * warning is legible rather than decorative.
 */

type SyntheticDataBannerProps = {
  /** Shown alongside the warning: mock means no model was called at all. */
  llmMode?: "mock" | "live";
  model?: string;
};

export function SyntheticDataBanner({ llmMode, model }: SyntheticDataBannerProps) {
  return (
    <div
      role="note"
      className="flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-amber-600/25 bg-amber-100/70 px-4 py-2 text-sm text-amber-900"
    >
      <span className="font-semibold">⚠️ All data synthetic</span>
      <span className="text-amber-800/80">
        Generated by <code className="font-mono text-xs">ledgerfab</code>. No real financial records.
      </span>

      {llmMode && (
        <span className="ml-auto flex items-center gap-1.5 text-xs text-amber-800/90">
          <span
            className={`size-1.5 rounded-full ${llmMode === "live" ? "bg-conf-high" : "bg-conf-mid"}`}
          />
          {llmMode === "live" ? (
            <>live model{model ? `: ${model}` : ""} — calls cost money</>
          ) : (
            <>mock model — no API calls, no spend</>
          )}
        </span>
      )}
    </div>
  );
}
