/**
 * aurora `SyntheticDataBanner` — spec 00 A2, and mandatory on every screenshot
 * (spec 00 A1 README order, spec 00 E definition of done, spec 11 section 11).
 *
 * It stays visible rather than being dismissible. A finance demo that could be mistaken for
 * real books is a liability, and the disclaimer is worth more on the screenshot than the
 * pixels it costs.
 */

type SyntheticDataBannerProps = {
  /** Shown alongside the warning: mock means no model was called at all. */
  llmMode?: "mock" | "live";
  model?: string;
};

export function SyntheticDataBanner({ llmMode, model }: SyntheticDataBannerProps) {
  return (
    <div
      role="note"
      className="flex flex-wrap items-center gap-x-3 gap-y-1 border-b border-amber-400/25 bg-amber-400/10 px-4 py-2 text-sm text-amber-200"
    >
      <span className="font-medium">⚠️ All data synthetic</span>
      <span className="text-amber-200/70">
        Generated by <code className="font-mono text-xs">ledgerfab</code>. No real financial records.
      </span>

      {llmMode && (
        <span className="ml-auto flex items-center gap-1.5 text-xs text-amber-200/70">
          <span className={`size-1.5 rounded-full ${llmMode === "live" ? "bg-conf-high" : "bg-conf-mid"}`} />
          {llmMode === "live" ? (
            <>
              live model{model ? `: ${model}` : ""} — calls cost money
            </>
          ) : (
            <>mock model — no API calls, no spend</>
          )}
        </span>
      )}
    </div>
  );
}
